tienda/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detalle, name='cart_detalle'),
    path('agregar/<int:producto_id>/', views.cart_agregar, name='cart_agregar'),
    path('remover/<int:producto_id>/', views.cart_remover, name='cart_remover'),
]

tienda/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('crear/', views.orden_create, name='orden_create'),
]

tienda/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.producto_lista, name='producto_lista'),
    path('<slug:categoria_slug>/', views.producto_lista, 
         name='producto_lista_por_categoria'),
    path('<int:id>/<slug:slug>/', views.producto_detalle, 
         name='producto_detalle'),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/cart/models.py
from django.db import models

# Create your models here.

tienda/orders/models.py
from django.db import models
from shop.models import Producto

class Orden(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField()
    direccion = models.CharField(max_length=250)
    codigo_postal = models.CharField(max_length=20)
    ciudad = models.CharField(max_length=100)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    pagado = models.BooleanField(default=False)

    class Meta:
        ordering = ['-creado']
        indexes = [
            models.Index(fields=['-creado']),
            ]
        verbose_name = 'orden'
        verbose_name_plural = 'órdenes'

    def __str__(self):
        return f'Orden {self.id}'
    
    def get_total_costo(self):
        return sum(item.get_costo() for item in self.items.all())

class OrdenItem(models.Model):
    orden = models.ForeignKey(Orden,
                              related_name='items',
                              on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto,
                                related_name='orden_items',
                                on_delete=models.CASCADE)
    precio = models.PositiveIntegerField()
    cantidad = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return str(self.id)

    def get_costo(self):
        return self.precio * self.cantidad

tienda/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ['nombre']
        indexes = [models.Index(fields=['nombre']),]
        verbose_name = 'categoría'
        verbose_name_plural = 'categorías'
    
    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return reverse('shop:producto_lista_por_categoria',
                       args=[self.slug])
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='productos', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    imagen = models.ImageField(upload_to='productos/%Y/%m/%d', blank=True)
    descripcion = models.TextField(blank=True)
    precio = models.PositiveIntegerField()
    disponible = models.BooleanField(default=True)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['nombre']
        indexes = [
        models.Index(fields=['id', 'slug']),
        models.Index(fields=['nombre']),
        models.Index(fields=['-creado']),
        ]
    
    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return reverse('shop:producto_detalle',
                       args=[self.id, self.slug])
    
    
    

tienda/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    cantidad = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    anular = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

tienda/orders/forms.py
from django import forms
from .models import Orden

class OrdenCreateForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = ['nombre', 'apellido', 'email', 'direccion',
                  'codigo_postal', 'ciudad']

tienda/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Producto
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_agregar(request, producto_id):
    cart = Cart(request)
    producto = get_object_or_404(Producto, id=producto_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.agregar(producto=producto,
                 cantidad=cd['cantidad'],
                 anular_cantidad=cd['anular'])
    return redirect('cart:cart_detalle')

@require_POST
def cart_remover(request, producto_id):
    cart = Cart(request)
    producto = get_object_or_404(Producto, id=producto_id)
    cart.remover(producto)
    return redirect('cart:cart_detalle')

def cart_detalle(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'cantidad': item['cantidad'],
            'anular': True})
    return render(request, 'cart/detalle.html', {'cart': cart})

tienda/orders/views.py
from django.shortcuts import render
# Create your views here.

from .models import OrdenItem
from .forms import OrdenCreateForm
from cart.cart import Cart

def orden_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrdenCreateForm(request.POST)
        if form.is_valid():
            orden = form.save()
            for item in cart:
                OrdenItem.objects.create(orden=orden,
                                         producto=item['producto'],
                                         precio=item['precio'],
                                         cantidad=item['cantidad'])
            # limpiar el carrito
            cart.limpiar()
            return render(request, 
                      'ordenes/orden/creado.html',
                      {'orden': orden})
    else:
        form = OrdenCreateForm()
    return render(request,
                  'ordenes/orden/crear.html',
                  {'cart': cart, 'form': form})

tienda/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Categoria, Producto
from cart.forms import CartAddProductForm

# Create your views here.

def producto_lista(request, categoria_slug=None):
    categoria = None
    categorias = Categoria.objects.all()
    productos = Producto.objects.filter(disponible=True)
    if categoria_slug:
        categoria = get_object_or_404(Categoria, slug=categoria_slug)
        productos = productos.filter(categoria=categoria)
    return render(request,
                  'shop/producto/lista.html',
                  {'categoria': categoria,
                   'categorias': categorias,
                   'productos': productos})

def producto_detalle(request, id, slug):
    producto = get_object_or_404(Producto, id=id, slug=slug, disponible=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/producto/detalle.html',
                  {'producto': producto,
                   'cart_product_form': cart_product_form})

tienda/cart/templates/cart/detalle.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Tu carrito de compra
{% endblock %}

{% block content %}
<h1>Tu carrito de compra</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Imagen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Remover</th>
            <th>Precio Unitario</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            {% with producto=item.producto %}
            <tr>
                <td>
                    <a href="{{ producto.get_absolute_url }}">
                        <img src="{% if producto.imagen %}{{ producto.imagen.url }}
                        {% else %}{% static "img/no_imagen.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ producto.nombre }}</td>
                <td>
                    <form action="{% url "cart:cart_agregar" producto.id %}" method="post">
                    {{ item.update_quantity_form.cantidad }}
                    {{ item.update_quantity_form.anular }}
                    <input type="submit" value="Actualizar">
                    {% csrf_token %}
                    </form>
                </td>
                <td>
                    <form action="{% url "cart:cart_remover" producto.id %}" method="post">
                        <input type="submit" value="Remover">
                        {% csrf_token %}
                    </form>
                </td>
                <td class="num">${{ item.precio }}</td>
                <td class="num">${{ item.total_precio }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_precio }}</td>
        </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url "shop:producto_lista" %}" class="button light">Seguir comprando</a>
    <a href="{% url "orders:orden_create" %}" class="button">Verificar pedido</a>
</p>
{% endblock %}

tienda/orders/templates/ordenes/orden/creado.html
{% extends "shop/base.html" %}
{% block title %}
    Gracias
{% endblock %}
{% block content %}
    <h1>Gracias</h1>
    <p>Tu orden ha sido completada satisfactoriamente. Tu número de orden es
    <strong>{{ orden.id }}</strong>.</p>
{% endblock %}

tienda/orders/templates/ordenes/orden/crear.html
{% extends "shop/base.html" %}

{% block title %}
    Verificar pedido
{% endblock %}

{% block content %}
<h1>Verificar pedido</h1>
<div class="order-info">
    <h3>Tu pedido</h3>
    <ul>
        {% for item in cart %}
            <li>
                {{ item.cantidad }}x {{ item.producto.nombre }}
                <span>₲{{ item.total_precio }}</span>
            </li>
        {% endfor %}
    </ul>
    <p>Total: {{ cart.get_total_precio }}</p>
</div>
<form method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Realizar pedido"></p>
    {% csrf_token %}
</form>
{% endblock %}

tienda/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Verde Vital{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>

    <body>
        <div id="header">
            <a href="/" class="logo">Verde Vital</a>
        </div>
        <div id="subheader">
            <div class="cart">
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                        Tu carrito:
                        <a href="{% url "cart:cart_detalle" %}">
                            {{ total_items }} item{{ total_items|pluralize }},
                            ₲{{ cart.get_total_precio }}
                        </a>
                    {% elif not orden %}
                        Tu carrito está vacío.
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>

</html>

tienda/shop/templates/shop/producto/detalle.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ producto.nombre }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if producto.imagen %}{{ producto.imagen.url }}
        {% else %}{% static "img/no_imagen.png" %}{% endif %}">
        <h1>{{ producto.nombre }}</h1>
        <h2>
            <a href="{{ producto.categoria.get_absolute_url }}">
                {{ producto.categoria }}
            </a>
        </h2>
        <p class="price">₲{{ producto.precio }}</p>
        <form action="{% url "cart:cart_agregar" producto.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Agregar al carrito">
            </form>
        {{ producto.descripcion|linebreaks }}
    </div>
{% endblock %}

tienda/shop/templates/shop/producto/lista.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if categoria %}{{ categoria.nombre }}{% else %}Productos{% endif %}
{% endblock %}

{% block content %}
<div id="sidebar">
    <h3>Categorías</h3>
    <ul>
        <li {% if not categoria %}class="selected" {% endif %}>
            <a href="{% url "shop:producto_lista" %}">Todo</a>
        </li>
        {% for c in categorias %}
            <li {% if categoria.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.nombre }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if categoria %}{{ categoria.nombre }}{% else %}Productos{% endif %}</h1>
    {% for producto in productos %}
        <div class="item">
            <a href="{{ producto.get_absolute_url }}">
                <img src="{% if producto.imagen %}{{ producto.imagen.url }}{% else %}{% static "img/no_imagen.png" %}{% endif %}">
            </a>
            <a href="{{ producto.get_absolute_url }}">{{ producto.nombre }}</a>
            <br>
            ₲{{ producto.precio }}
        </div>
    {% endfor %}
</div>
{% endblock %}